// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: MIT-0

import { MarketPlaceItem } from '../pages/table-quick-saved-filters/interface';

const items: MarketPlaceItem[] = [
  {
    id: 'websoft-neo4j',
    name: 'Cloud Database Service for Neo4j',
    vendorName: 'Websoft9',
    rating: 0,
    numberOfReviews: 0,
    freeTrial: 'Yes',
    yearlyPrice: 2400,
    pricingModel: 'Usage based',
    category: 'Databases',
    deliveryMethod: 'Amazon Machine Image',
    operatingSystem: 'Ubuntu',
    region: 'us-east-1',
    architecture: '64-bit (x86)',
    description:
      'This is a cloud-native Neo4j® graph database on the Websoft9 Applications Hosting Platform. It is always up-to-date, secure, and ready to use right out of the box with business support from Websoft9.',
    contractType: 'Standard',
  },
  {
    id: 'neo4j-Aura',
    name: 'Neo4j Aura',
    vendorName: 'Neo4j',
    rating: 0,
    numberOfReviews: 0,
    freeTrial: 'No',
    yearlyPrice: 0,
    pricingModel: 'Usage based',
    category: 'Databases',
    deliveryMethod: 'CloudFormation Template',
    operatingSystem: 'Amazon Linux',
    region: 'us-east-1',
    architecture: '64-bit (x86)',
    description:
      'Battle tested for performance, Neo4j is the only enterprise-strength graph database that combines native graph storage, scalable speed-optimized architecture, and ACID compliance. The high-performance distributed cluster architecture of Neo4j enables the most challenging OLTP and data science workloads.',
    contractType: 'Standard',
  },
  {
    id: 'weather-us-history',
    name: 'Historical Weather Summary Report - United States',
    vendorName: 'Weather Trends International',
    rating: null,
    numberOfReviews: null,
    freeTrial: 'No',
    yearlyPrice: 3000,
    pricingModel: 'Upfront commitment',
    category: 'Data products',
    deliveryMethod: 'Amazon S3 object',
    operatingSystem: '-',
    region: 'us-west-2',
    architecture: '-',
    description:
      'Battle tested for performance, Neo4j is the only enterprise-strength graph database that combines native graph storage, scalable speed-optimized architecture, and ACID compliance. The high-performance distributed cluster architecture of Neo4j enables the most challenging OLTP and data science workloads.',
    contractType: 'Standard Data Subscription Agreement',
  },
  {
    id: 'crowdstrike-falcon',
    name: 'CrowdStrike Falcon Endpoint Protection',
    vendorName: 'CrowdStrike',
    rating: 2.3,
    numberOfReviews: 3,
    freeTrial: 'No',
    yearlyPrice: 323.99,
    pricingModel: 'Upfront commitment',
    category: 'Security',
    deliveryMethod: 'SaaS',
    operatingSystem: '-',
    region: '-',
    architecture: '-',
    description: 'Stop breaches with unified endpoint protection delivered from the cloud.',
    contractType: 'Standard',
  },
  {
    id: 'datadog',
    name: 'Datadog Pro',
    vendorName: 'Datadog',
    rating: 4.5,
    numberOfReviews: 32,
    freeTrial: 'No',
    yearlyPrice: 180,
    pricingModel: 'Upfront commitment',
    category: 'Monitoring',
    deliveryMethod: 'SaaS',
    operatingSystem: '-',
    region: '-',
    architecture: '-',
    description:
      'Datadog is a SaaS-based unified observability and security platform providing full visibility into the health and performance of each layer of your environment at a glance. Datadog allows you to customize this insight to your stack by collecting and correlating data from more than 600 vendor-backed technologies and APM libraries, all in a single pane of glass. Monitor your underlying infrastructure, supporting services, applications alongside security data in a single observability platform.',
    contractType: 'Standard',
  },
  {
    id: 'monday',
    name: 'monday.com work management',
    vendorName: 'monday.com',
    rating: 2,
    numberOfReviews: 1,
    freeTrial: 'No',
    yearlyPrice: 31200,
    pricingModel: 'Upfront commitment',
    category: 'CRM',
    deliveryMethod: 'SaaS',
    operatingSystem: '-',
    region: '-',
    architecture: '-',
    description:
      'monday.com work management is a low-code/no-code work management platform that empowers organizations to connect teams and business units, enhances organizational agility, creates a unifying workspace across departments, and increases operational efficiency and productivity.',
    contractType: 'Standard',
  },
  {
    id: 'kafka-ui',
    name: 'UI for Apache Kafka',
    vendorName: 'Provectus',
    rating: 0,
    numberOfReviews: 0,
    freeTrial: 'No',
    yearlyPrice: 0,
    pricingModel: 'Free',
    category: 'Data analytics',
    deliveryMethod: 'Amazon Machine Image',
    operatingSystem: 'AmazonLinux',
    region: 'us-east-1',
    architecture: '64-bit (x86)',
    description: 'Free, open-source web UI to monitor and manage Apache Kafka clusters.',
    contractType: 'Standard',
  },
  {
    id: 'cardx1',
    name: 'OpenVPN',
    vendorName: 'OpenVPN Inc.',
    rating: 4,
    numberOfReviews: 1,
    freeTrial: 'No',
    yearlyPrice: 840,
    pricingModel: 'Usage based',
    category: 'Security',
    deliveryMethod: 'Amazon Machine Image',
    operatingSystem: 'Ubuntu',
    region: 'us-east-1',
    architecture: '64-bit (x86)',
    description:
      'OpenVPN Access Server is a self-hosted enterprise-grade business software VPN solution that provides a securely encrypted connection to networks like on AWS.',
    contractType: 'Standard',
  },
  {
    id: 'windows-server',
    name: 'Microsoft Windows Server 2022 Base',
    vendorName: 'AWS',
    rating: 0,
    numberOfReviews: 0,
    freeTrial: 'No',
    yearlyPrice: 0,
    pricingModel: 'Free',
    category: 'Operating Systems',
    deliveryMethod: 'Amazon Machine Image',
    operatingSystem: 'Win2022',
    region: 'us-west-2',
    architecture: '64-bit (x86)',
    description:
      "Amazon EC2 running Microsoft Windows Server is a fast and dependable environment for deploying applications using the Microsoft Web Platform. Amazon EC2 enables you to run compatible Windows-based solutions on AWS' high-performance, reliable, cost-effective, cloud computing platform.",
    contractType: 'Standard',
  },
  {
    id: 'weather-europe-history',
    name: 'Historical Weather Summary Report - Europe',
    vendorName: 'Weather Trends International',
    rating: null,
    numberOfReviews: null,
    freeTrial: 'No',
    yearlyPrice: 3000,
    pricingModel: 'Upfront commitment',
    category: 'Data products',
    deliveryMethod: 'Amazon S3 object',
    operatingSystem: '-',
    region: 'us-west-2',
    architecture: '-',
    description: '',
    contractType: 'Standard Data Subscription Agreement',
  },
  {
    id: 'snowflake',
    name: 'Snowflake Connector for AWS Glue',
    vendorName: 'AWS',
    rating: 1,
    numberOfReviews: 1,
    freeTrial: 'No',
    yearlyPrice: 0,
    pricingModel: 'Free',
    category: 'Data integration',
    deliveryMethod: 'Container image',
    operatingSystem: 'Linux',
    region: 'us-west-2',
    architecture: '64-bit (x86)',
    description: 'Easily connect to Snowflake from AWS Glue',
    contractType: 'Standard',
  },
  {
    id: 'grafana',
    name: 'Grafana Enterprise',
    vendorName: 'Grafana Labs',
    rating: 0,
    numberOfReviews: 0,
    freeTrial: 'No',
    yearlyPrice: 40000,
    pricingModel: 'Upfront commitment',
    category: 'Monitoring',
    deliveryMethod: 'Container image',
    operatingSystem: 'Linux',
    region: 'us-east-1',
    architecture: '64-bit (x86)',
    description:
      'Upgrade open-source Grafana with premium data sources, access control, reporting and other functionality, as well as support and professional services from Grafana Labs, the creators of Grafana. ',
    contractType: 'Standard',
  },
  {
    id: 'similarweb',
    name: 'Similarweb Single Market Data Feed',
    vendorName: 'Similarweb',
    rating: null,
    numberOfReviews: null,
    freeTrial: 'No',
    yearlyPrice: 22000,
    pricingModel: 'Upfront commitment',
    category: 'Data products',
    deliveryMethod: 'Amazon S3 object data set',
    operatingSystem: '-',
    region: '-',
    architecture: '-',
    description: 'Similarweb data feed for a single market providing estimated website visitor counts.',
    contractType: 'Standard',
  },
  {
    id: 'kubecost',
    name: 'Kubecost',
    vendorName: 'Kubecost',
    rating: 0,
    numberOfReviews: 2,
    freeTrial: 'Yes',
    yearlyPrice: 0,
    pricingModel: 'Usage based',
    category: 'Analytics platforms',
    deliveryMethod: 'Container image',
    operatingSystem: 'Linux',
    region: 'us-east-1',
    architecture: '64-bit (x86)',
    description: 'Free, open-source web UI to monitor and manage Apache Kafka clusters.',
    contractType: 'Standard',
  },
  {
    id: 'websoft-neo4j2',
    name: 'Cloud Database Service for Neo4j',
    vendorName: 'Websoft9',
    rating: 0,
    numberOfReviews: 0,
    freeTrial: 'Yes',
    yearlyPrice: 2400,
    pricingModel: 'Usage based',
    category: 'Databases',
    deliveryMethod: 'Amazon Machine Image',
    operatingSystem: 'Ubuntu',
    region: 'us-east-1',
    architecture: '64-bit (x86)',
    description:
      'This is a cloud-native Neo4j® graph database on the Websoft9 Applications Hosting Platform. It is always up-to-date, secure, and ready to use right out of the box with business support from Websoft9.',
    contractType: 'Standard',
  },
  {
    id: 'neo4j-Aura2',
    name: 'Neo4j Aura',
    vendorName: 'Neo4j',
    rating: 0,
    numberOfReviews: 0,
    freeTrial: 'No',
    yearlyPrice: 0,
    pricingModel: 'Usage based',
    category: 'Databases',
    deliveryMethod: 'CloudFormation Template',
    operatingSystem: 'Amazon Linux',
    region: 'us-east-1',
    architecture: '64-bit (x86)',
    description:
      'Battle tested for performance, Neo4j is the only enterprise-strength graph database that combines native graph storage, scalable speed-optimized architecture, and ACID compliance. The high-performance distributed cluster architecture of Neo4j enables the most challenging OLTP and data science workloads.',
    contractType: 'Standard',
  },
  {
    id: 'weather-us-history2',
    name: 'Historical Weather Summary Report - United States',
    vendorName: 'Weather Trends International',
    rating: null,
    numberOfReviews: null,
    freeTrial: 'No',
    yearlyPrice: 3000,
    pricingModel: 'Upfront commitment',
    category: 'Data products',
    deliveryMethod: 'Amazon S3 object',
    operatingSystem: '-',
    region: 'us-west-2',
    architecture: '-',
    description:
      'Battle tested for performance, Neo4j is the only enterprise-strength graph database that combines native graph storage, scalable speed-optimized architecture, and ACID compliance. The high-performance distributed cluster architecture of Neo4j enables the most challenging OLTP and data science workloads.',
    contractType: 'Standard Data Subscription Agreement',
  },
  {
    id: 'crowdstrike-falcon2',
    name: 'CrowdStrike Falcon Endpoint Protection',
    vendorName: 'CrowdStrike',
    rating: 2.3,
    numberOfReviews: 3,
    freeTrial: 'No',
    yearlyPrice: 323.99,
    pricingModel: 'Upfront commitment',
    category: 'Security',
    deliveryMethod: 'SaaS',
    operatingSystem: '-',
    region: '-',
    architecture: '-',
    description: 'Stop breaches with unified endpoint protection delivered from the cloud.',
    contractType: 'Standard',
  },
  {
    id: 'datadog2',
    name: 'Datadog Pro',
    vendorName: 'Datadog',
    rating: 4.5,
    numberOfReviews: 32,
    freeTrial: 'No',
    yearlyPrice: 180,
    pricingModel: 'Upfront commitment',
    category: 'Monitoring',
    deliveryMethod: 'SaaS',
    operatingSystem: '-',
    region: '-',
    architecture: '-',
    description:
      'Datadog is a SaaS-based unified observability and security platform providing full visibility into the health and performance of each layer of your environment at a glance. Datadog allows you to customize this insight to your stack by collecting and correlating data from more than 600 vendor-backed technologies and APM libraries, all in a single pane of glass. Monitor your underlying infrastructure, supporting services, applications alongside security data in a single observability platform.',
    contractType: 'Standard',
  },
  {
    id: 'monday2',
    name: 'monday.com work management',
    vendorName: 'monday.com',
    rating: 2,
    numberOfReviews: 1,
    freeTrial: 'No',
    yearlyPrice: 31200,
    pricingModel: 'Upfront commitment',
    category: 'CRM',
    deliveryMethod: 'SaaS',
    operatingSystem: '-',
    region: '-',
    architecture: '-',
    description:
      'monday.com work management is a low-code/no-code work management platform that empowers organizations to connect teams and business units, enhances organizational agility, creates a unifying workspace across departments, and increases operational efficiency and productivity.',
    contractType: 'Standard',
  },
  {
    id: 'kafka-ui2',
    name: 'UI for Apache Kafka',
    vendorName: 'Provectus',
    rating: 0,
    numberOfReviews: 0,
    freeTrial: 'No',
    yearlyPrice: 0,
    pricingModel: 'Free',
    category: 'Data analytics',
    deliveryMethod: 'Amazon Machine Image',
    operatingSystem: 'AmazonLinux',
    region: 'us-east-1',
    architecture: '64-bit (x86)',
    description: 'Free, open-source web UI to monitor and manage Apache Kafka clusters.',
    contractType: 'Standard',
  },
  {
    id: 'cardx2',
    name: 'OpenVPN',
    vendorName: 'OpenVPN Inc.',
    rating: 4,
    numberOfReviews: 1,
    freeTrial: 'No',
    yearlyPrice: 840,
    pricingModel: 'Usage based',
    category: 'Security',
    deliveryMethod: 'Amazon Machine Image',
    operatingSystem: 'Ubuntu',
    region: 'us-east-1',
    architecture: '64-bit (x86)',
    description:
      'OpenVPN Access Server is a self-hosted enterprise-grade business software VPN solution that provides a securely encrypted connection to networks like on AWS.',
    contractType: 'Standard',
  },
  {
    id: 'windows-server2',
    name: 'Microsoft Windows Server 2022 Base',
    vendorName: 'AWS',
    rating: 0,
    numberOfReviews: 0,
    freeTrial: 'No',
    yearlyPrice: 0,
    pricingModel: 'Free',
    category: 'Operating Systems',
    deliveryMethod: 'Amazon Machine Image',
    operatingSystem: 'Win2022',
    region: 'us-west-2',
    architecture: '64-bit (x86)',
    description:
      "Amazon EC2 running Microsoft Windows Server is a fast and dependable environment for deploying applications using the Microsoft Web Platform. Amazon EC2 enables you to run compatible Windows-based solutions on AWS' high-performance, reliable, cost-effective, cloud computing platform.",
    contractType: 'Standard',
  },
  {
    id: 'weather-europe-history2',
    name: 'Historical Weather Summary Report - Europe',
    vendorName: 'Weather Trends International',
    rating: null,
    numberOfReviews: null,
    freeTrial: 'No',
    yearlyPrice: 3000,
    pricingModel: 'Upfront commitment',
    category: 'Data products',
    deliveryMethod: 'Amazon S3 object',
    operatingSystem: '-',
    region: 'us-west-2',
    architecture: '-',
    description: '',
    contractType: 'Standard Data Subscription Agreement',
  },
  {
    id: 'snowflake2',
    name: 'Snowflake Connector for AWS Glue',
    vendorName: 'AWS',
    rating: 1,
    numberOfReviews: 1,
    freeTrial: 'No',
    yearlyPrice: 0,
    pricingModel: 'Free',
    category: 'Data integration',
    deliveryMethod: 'Container image',
    operatingSystem: 'Linux',
    region: 'us-west-2',
    architecture: '64-bit (x86)',
    description: 'Easily connect to Snowflake from AWS Glue',
    contractType: 'Standard',
  },
  {
    id: 'grafana2',
    name: 'Grafana Enterprise',
    vendorName: 'Grafana Labs',
    rating: 0,
    numberOfReviews: 0,
    freeTrial: 'No',
    yearlyPrice: 40000,
    pricingModel: 'Upfront commitment',
    category: 'Monitoring',
    deliveryMethod: 'Container image',
    operatingSystem: 'Linux',
    region: 'us-east-1',
    architecture: '64-bit (x86)',
    description:
      'Upgrade open-source Grafana with premium data sources, access control, reporting and other functionality, as well as support and professional services from Grafana Labs, the creators of Grafana. ',
    contractType: 'Standard',
  },
  {
    id: 'similarweb2',
    name: 'Similarweb Single Market Data Feed',
    vendorName: 'Similarweb',
    rating: null,
    numberOfReviews: null,
    freeTrial: 'No',
    yearlyPrice: 22000,
    pricingModel: 'Upfront commitment',
    category: 'Data products',
    deliveryMethod: 'Amazon S3 object data set',
    operatingSystem: '-',
    region: '-',
    architecture: '-',
    description: 'Similarweb data feed for a single market providing estimated website visitor counts.',
    contractType: 'Standard',
  },
  {
    id: 'kubecost2',
    name: 'Kubecost',
    vendorName: 'Kubecost',
    rating: 0,
    numberOfReviews: 2,
    freeTrial: 'Yes',
    yearlyPrice: 0,
    pricingModel: 'Usage based',
    category: 'Analytics platforms',
    deliveryMethod: 'Container image',
    operatingSystem: 'Linux',
    region: 'us-east-1',
    architecture: '64-bit (x86)',
    description: 'Free, open-source web UI to monitor and manage Apache Kafka clusters.',
    contractType: 'Standard',
  },
];

export default items;
